import vtk
import time

reader1 = vtk.vtkSTLReader()
reader1.SetFileName("arm.stl")
reader2 = vtk.vtkSTLReader()
reader2.SetFileName("arm_motor_base.stl")
reader3 = vtk.vtkSTLReader()
reader3.SetFileName("arming_arm.stl")
reader4 = vtk.vtkSTLReader()
reader4.SetFileName("base_motor_mount.stl")
reader5 = vtk.vtkSTLReader()
reader5.SetFileName("base.stl")
reader6 = vtk.vtkSTLReader()
reader6.SetFileName("controller_bottom.stl")
reader7 = vtk.vtkSTLReader()
reader7.SetFileName("controller_top.stl")
reader8 = vtk.vtkSTLReader()
reader8.SetFileName("plate.stl")
reader9 = vtk.vtkSTLReader()
reader9.SetFileName("tray_gate.stl")
reader10 = vtk.vtkSTLReader()
reader10.SetFileName("tray.stl")

stlMapper1 = vtk.vtkPolyDataMapper()
stlMapper1.SetInputConnection(reader1.GetOutputPort())
stlMapper2 = vtk.vtkPolyDataMapper()
stlMapper2.SetInputConnection(reader2.GetOutputPort())
stlMapper3 = vtk.vtkPolyDataMapper()
stlMapper3.SetInputConnection(reader3.GetOutputPort())
stlMapper4 = vtk.vtkPolyDataMapper()
stlMapper4.SetInputConnection(reader4.GetOutputPort())
stlMapper5 = vtk.vtkPolyDataMapper()
stlMapper5.SetInputConnection(reader5.GetOutputPort())
stlMapper6 = vtk.vtkPolyDataMapper()
stlMapper6.SetInputConnection(reader6.GetOutputPort())
stlMapper7 = vtk.vtkPolyDataMapper()
stlMapper7.SetInputConnection(reader7.GetOutputPort())
stlMapper8 = vtk.vtkPolyDataMapper()
stlMapper8.SetInputConnection(reader8.GetOutputPort())
stlMapper9 = vtk.vtkPolyDataMapper()
stlMapper9.SetInputConnection(reader9.GetOutputPort())
stlMapper10 = vtk.vtkPolyDataMapper()
stlMapper10.SetInputConnection(reader10.GetOutputPort())

property = vtk.vtkProperty()
property.SetColor(0, 1, 0)
property.SetDiffuse(0.7)
property.SetSpecular(0.4)
property.SetSpecularPower(20)

coneActor1 = vtk.vtkActor()
coneActor1.SetMapper(stlMapper1)
coneActor1.SetProperty(property)
coneActor1.SetPosition(20, 17, -122)
coneActor1.SetOrigin(-20, -17, 122)
coneActor2 = vtk.vtkActor()
coneActor2.SetMapper(stlMapper2)
coneActor2.SetProperty(property)
coneActor2.SetPosition(20, 17, -122)
coneActor2.SetOrigin(-20, -17, 122)
coneActor3 = vtk.vtkActor()
coneActor3.SetMapper(stlMapper3)
coneActor3.SetProperty(property)
coneActor3.SetPosition(20, 17, -122)
coneActor3.SetOrigin(-20, -17, 122)
coneActor4 = vtk.vtkActor()
coneActor4.SetMapper(stlMapper4)
coneActor4.SetProperty(property)
coneActor4.SetPosition(20, 17, -122)
coneActor4.SetOrigin(-20, -17, 122)
coneActor5 = vtk.vtkActor()
coneActor5.SetMapper(stlMapper5)
coneActor5.SetProperty(property)
coneActor5.SetPosition(20, 17, -122)
coneActor5.SetOrigin(-20, -17, 122)
coneActor6 = vtk.vtkActor()
coneActor6.SetMapper(stlMapper6)
coneActor6.SetProperty(property)
coneActor6.SetPosition(20, 17, -122)
coneActor6.SetOrigin(-20, -17, 122)
coneActor7 = vtk.vtkActor()
coneActor7.SetMapper(stlMapper7)
coneActor7.SetProperty(property)
coneActor7.SetPosition(20, 17, -122)
coneActor7.SetOrigin(-20, -17, 122)
coneActor8 = vtk.vtkActor()
coneActor8.SetMapper(stlMapper8)
coneActor8.SetProperty(property)
coneActor8.SetPosition(20, 17, -122)
coneActor8.SetOrigin(-20, -17, 122)
coneActor9 = vtk.vtkActor()
coneActor9.SetMapper(stlMapper9)
coneActor9.SetProperty(property)
coneActor9.SetPosition(20, 17, -122)
coneActor9.SetOrigin(-20, -17, 122)
coneActor10 = vtk.vtkActor()
coneActor10.SetMapper(stlMapper10)
coneActor10.SetProperty(property)
coneActor10.SetPosition(20, 17, -122)
coneActor10.SetOrigin(-20, -17, 122)

ren = vtk.vtkRenderer()
ren.AddActor(coneActor1)
ren.AddActor(coneActor2)
ren.AddActor(coneActor3)
ren.AddActor(coneActor4)
ren.AddActor(coneActor5)
ren.AddActor(coneActor6)
ren.AddActor(coneActor7)
ren.AddActor(coneActor8)
ren.AddActor(coneActor9)
ren.AddActor(coneActor10)
ren.SetBackground(0.1, 0.2, 0.4)

renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren)
renWin.SetSize(1200, 1200)

for i in range(0, 40):
    time.sleep(0.1)
    renWin.Render()
    ren.GetActiveCamera().Azimuth(1)
for i in range(0, 20):
    time.sleep(0.1)
    renWin.Render()
    coneActor1.RotateX(1)
    coneActor3.RotateX(1)
    ren.GetActiveCamera().Azimuth(1)
for i in range(0, 40):
    time.sleep(0.1)
    renWin.Render()
    ren.GetActiveCamera().Azimuth(1)
